Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@avichen 
0
0912avichen/OpenWrt-CI
forked from KFERMercer/OpenWrt-CI
 Code Pull requests 0 Actions Projects 0 Wiki Security Insights Settings
OpenWrt-CI
/
openwrt-ci.yml
 

1
#
2
# This is free software, lisence use MIT.
3
# 
4
# Copyright (C) 2019 P3TERX <https://p3terx.com>
5
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
6
# 
7
# <https://github.com/KFERMercer/OpenWrt-CI>
8
#
9
​
10
name: OpenWrt-CI
11
​
12
on:
13
  push:
14
    branches: 
15
      - master
16
  # schedule:
17
  #   - cron: 0 20 * * *
18
  # release:
19
  #   types: [published]
20
​
21
jobs:
22
​
23
  build:
24
​
25
    runs-on: ubuntu-latest
26
​
27
    steps:
28
​
29
      - name: Checkout
30
        uses: actions/checkout@master
31
        with:
32
          ref: master
33
​
34
      - name: Initialization environment
35
        env:
36
          DEBIAN_FRONTEND: noninteractive
37
        run: |
38
          docker rmi `docker images -q`
39
          echo "Deleting files, please wait ..."
40
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php
41
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
42
          sudo -E apt-get update
43
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
44
          sudo -E apt-get -y autoremove --purge
45
          sudo -E apt-get clean
46
​
47
      - name: Update feeds
48
        run: |
49
          ./scripts/feeds update -a
@avichen
Commit changes
Commit summary
Update openwrt-ci.yml
Optional extended description
Add an optional extended description…
 Commit directly to the master branch.
 Create a new branch for this commit and start a pull request. Learn more about pull requests.
 
© 2019 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
Login to unlock more features
avichen / OpenWrt-CI
master
LICENSE
README.md
merge-upstream.yml
openwrt-ci.yml
